name: Code Reviewer
run-name: Action started by ${{ github.actor }}

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Code Review the pull request
        uses: ./code-review
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          openai_key: ${{ secrets.OPENAI_KEY }}
          max_tokens: 900
          exclude: "**/*.json, **/*.md, **/*.g.dart"
          append_prompt: |
            - Give a minimum of 0 suggestions and a maximum of 5 suggestions.
            - Translate the comment in all "reviewComment" properties to portuguese (pt-br).