name: Generate Enhanced Release Notes
run-name: Action started by ${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag of the release.'
        required: true
        type: string

jobs:
  enhanced_release_notes:
    name: Generate Enhanced Release Notes
    runs-on: ubuntu-latest

    outputs:
      enhanced_notes: ${{ steps.release_notes.outputs.enhanced_notes }}
      release_notes: ${{ steps.release_notes.outputs.release_notes }}

    steps:
    - uses: actions/checkout@v4 
    
    - uses: ./generate-enhanced-notes
      id: release_notes
      with:
        tag_name: ${{ github.event.inputs.tagName }}
        use_previous_tag_latest_release: true
        verbose: true
        token:  ${{ secrets.GITHUB_TOKEN }}
        openai_key: ${{ secrets.OPENAI_KEY }}
        max_tokens: 400
        prompt: Gere notas de lançamento em português, para novos os recursos do aplicativo XYZ. As notas devem ser comerciais, genéricas e estritamentes sucintas. O objetivo é que as notas de lançamento sejam usadas para promover o aplicativo e não para descrever as alteração.

    - name: Print Release Notes (Use it as you want)
      run: | 
        echo "${{ steps.release_notes.outputs.enhanced_notes }}"
        echo "${{ steps.release_notes.outputs.enhanced_notes }}" >> $GITHUB_STEP_SUMMARY

  show_enhanced_release_notes:
    name: Read Outputs from First Job
    runs-on: ubuntu-latest
    needs: enhanced_release_notes
    steps:
    - name: Print Release Notes (Use it as you want)
      run: |
        echo "---"
        echo "${{ needs.enhanced_release_notes.outputs.release_notes }}"
        echo "---"
        echo "${{ needs.enhanced_release_notes.outputs.enhanced_notes }}"