name: Generate Enhanced Release Notes
run-name: Action started by ${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag of the release.'
        required: true
        type: string

jobs:
  print_enhanced_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Release Notes
        id: release_notes
        uses: ./generate-enhanced-notes
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ github.event.inputs.tagName }}
          openai_key: "${{ secrets.OPENAI_KEY }}"
          use_previous_tag_latest_release: true
          verbose: true

      - name: Print Release Notes (Use it as you want)
        run: echo "${{ steps.release_notes.outputs.enhanced_notes }}"